import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

// TODO: change
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-full flex m-auto">
      <body className={twMerge("m-auto bg-background", inter.className)}>
        <Header />
        <main className="bg-card text-card-foreground p-8 text-center rounded-lg my-4">
          {children}
        </main>
      </body>
    </html>
  );
}
