import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { twMerge } from "tailwind-merge";
import { PropsWithChildren, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

// TODO: change
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps extends PropsWithChildren {
  additionalCard: ReactNode;
}

export default function RootLayout({
  children,
  additionalCard,
}: Readonly<LayoutProps>) {
  return (
    <html lang="en" className="size-full flex m-auto">
      <body className={twMerge("m-auto bg-background", inter.className)}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
